# Generated by Django 4.1.2 on 2022-12-20 02:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "designation",
            },
        ),
        migrations.CreateModel(
            name="NewsLetterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("date_subscribed", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "news_letter_subscribers",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(blank=True, max_length=80)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "is_student",
                    models.BooleanField(default=True, verbose_name="Student"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("username", models.CharField(max_length=40, unique=True)),
                ("password", models.CharField(editable=False, max_length=100)),
                (
                    "avatar",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        default="accounts/avatars/default.png",
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[370, 259],
                        upload_to="accounts/avatars",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.designation",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
    ]
