# Generated by Django 4.1.4 on 2023-01-08 13:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_member_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="courses/thumbnails/placeholder.png",
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[600, 400],
                upload_to="courses/thumbnails/",
            ),
        ),
    ]
